Description:  Elastic Beanstalk environment created in the default VPC. Not currently used by takeover code.

Parameters:
  DomainName:
    Description: target domain
    Type: String
  BucketName:
    Description: S3 bucket for application content
    Type: String
Resources:
  takeoverApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Takeover Application
  takeoverApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: takeoverApplication
      Description: AWS ElasticBeanstalk Takeover Application Version
      SourceBundle:
        S3Bucket: !Ref BucketName
        S3Key: content.zip
  takeoverConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: takeoverApplication
      Description: AWS ElasticBeanstalk Takeover Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '1'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref TakeoverInstanceProfile       
      SolutionStackName: 64bit Amazon Linux 2 v3.3.9 running PHP 8.0
  takeoverEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: takeoverApplication
      CNAMEPrefix: 
        !Ref DomainName
      Description: AWS ElasticBeanstalk Takeover Environment
      TemplateName:
        Ref: takeoverConfigurationTemplate
      VersionLabel:
        Ref: takeoverApplicationVersion
  TakeoverInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
  TakeoverInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref TakeoverInstanceRole  